version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: PotatoHD
      POSTGRES_PASSWORD: password
      POSTGRES_DB: java
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./backend
    container_name: api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "3001:3001"
  frontend:
    build: ./frontend #This specifies the location of our Dockerfile
    context: ./frontend #This specifies the location of our Dockerfile
    command: prod
    ports: #This is used to map the container’s ports to the host machine.
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: